#.travis.yml

sudo: required  
dist: trusty

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch false
  - ng build --prod --aot

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "dancing-clover"
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change

cache:
  directories:
    - node_modules